### ISSUE TITLE
Build fails with SocketTimeoutException & ConnectException

### ISSUE THREAD

**Issue by pranavgore09** [fabric8io/fabric8-build-team#34]
I observed these two failures in mentioned builds

Error SocketTimeoutException found [here](https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2426/65/console)
```
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connec
```

Error ConnectException found [here](https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/job/PR-2426/66/console) 
```
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
```

**Comment by piyush-garg** [comment]
we have shut down GKE. closing this.
