### ISSUE TITLE
Fails with error 'Cannot contact jenkins-slave-38xc0-81nf9' 

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#35]
Build for openshift-jenkins-s2i-config fails on master.

https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8io-auto-rel%2Fopenshift-jenkins-s2i-config/detail/PR-141/1/pipeline

```
java.io.EOFException

	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Cannot contact jenkins-slave-38xc0-81nf9: java.io.IOException: remote file operation failed: /home/jenkins/workspace/t-jenkins-s2i-config_PR-141-WDWXTPIJPXJLJKXPGSZD7MKG3CAJGEESGNRSBYMHMXIIDOILVUJA at hudson.remoting.Channel@2a024d89:Channel to /10.12.15.62: hudson.remoting.ChannelClosedException: Remote call on Channel to /10.12.15.62 failed. The channel is closing down or has closed down

missing workspace /home/jenkins/workspace/t-jenkins-s2i-config_PR-141-WDWXTPIJPXJLJKXPGSZD7MKG3CAJGEESGNRSBYMHMXIIDOILVUJA on jenkins-slave-38xc0-81nf9
```

**Comment by piyush-garg** [comment]
we have moved this to CICO. closing this
